scene.setBackgroundColor(7)
tiles.setTilemap(tilemap`bottom`)
let playerSprite = sprites.create(assets.image`default`, SpriteKind.Player)
scene.cameraFollowSprite(playerSprite)
tiles.placeOnTile(playerSprite, tiles.getTileLocation(9, 0))
